In [10]:
from random import shuffle

from pandas.conftest import axis_1

""""Numpy Random"""
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(3, 5))
print(type(np.random.rand(5)))

0.3655767203037744
[0.69729631 0.55074099 0.2632526  0.11095932 0.48187166]
[[0.51040865 0.35838719 0.27225286 0.02489808 0.25772109]
 [0.54662123 0.2087066  0.50463408 0.26023099 0.48579585]
 [0.51928354 0.78406955 0.24912857 0.27991949 0.5643667 ]]
<class 'numpy.ndarray'>


In [17]:
print(np.random.randint(100))
print(np.random.randint(100, size=(3, 4)))

51
[[34 84 62 59]
 [33 79 98 57]
 [14 74 20 82]]


In [24]:
random_array = np.random.randint(30, size=(10))
print(random_array)

[28 25 27 24 23 29 18 16 13 13]


In [28]:
np.random.shuffle(random_array)
print(random_array)

[27 13 23 18 13 24 16 29 25 28]


In [30]:
"""" Spliting dataset into training, testing and validation"""
data_set = np.random.randint(100, size=(50, 3))
print("Data set:\n ", data_set[:5])

Data set:
  [[ 3 90 25]
 [55 16 29]
 [33 57 64]
 [ 5 58 81]
 [46 28  2]]


In [31]:
np.random.shuffle(data_set)
print(data_set[:5])

[[55 16 29]
 [49 25 17]
 [47 43 21]
 [52 37  9]
 [52 25 92]]


In [32]:
""""Spliting dataset"""
index_1 = int(0.8 * len(data_set))
index_2 = int(0.9 * len(data_set))
training, testing, validation = np.split(
    data_set, [index_1, index_2]
)
print(len(training), len(testing), len(validation))

40 5 5


Numpy Axis


In [33]:
My_random_array = np.random.randint(50, size=(4, 3))
print(My_random_array)

[[14  7  3]
 [41 33 16]
 [27 18 44]
 [49 42 19]]


In [36]:
print(np.sum(My_random_array))
print(np.sum(My_random_array, axis=1))
print(np.sum(My_random_array, axis=0))

313
[ 24  90  89 110]
[131 100  82]


In [37]:
random_3d_array = np.random.randint(100, size=(2, 4, 3))
print(random_3d_array)

[[[54 10 13]
  [29 23  4]
  [77 82 46]
  [23 29 47]]

 [[96 56 86]
  [ 0 50 80]
  [73 53 24]
  [66 85 63]]]


In [39]:
print(np.sum(random_3d_array, axis= 0))
print(np.sum(random_3d_array, axis= 1))
print(np.sum(random_3d_array, axis= 2))
print(np.sum(random_3d_array, axis= 0).shape)
print(np.sum(random_3d_array, axis= 1).shape)
print(np.sum(random_3d_array, axis= 2).shape)

[[150  66  99]
 [ 29  73  84]
 [150 135  70]
 [ 89 114 110]]
[[183 144 110]
 [235 244 253]]
[[ 77  56 205  99]
 [238 130 150 214]]
(4, 3)
(2, 3)
(2, 4)


In [40]:
my_1d_array_random = np.random.randint(100, size=(15,))
print(my_1d_array_random)

[94 74  9 45 93 29 47 35 95 82 14 52 80 83 66]


In [42]:
my_1d_array_random_splited = np.split(
    my_1d_array_random,
    indices_or_sections=5
)
print(my_1d_array_random_splited)
print(my_1d_array_random_splited[0])
print(my_1d_array_random_splited[1])
print(my_1d_array_random_splited[2])

[array([94, 74,  9], dtype=int32), array([45, 93, 29], dtype=int32), array([47, 35, 95], dtype=int32), array([82, 14, 52], dtype=int32), array([80, 83, 66], dtype=int32)]
[94 74  9]
[45 93 29]
[47 35 95]


In [43]:
dot_product = np.dot(my_1d_array_random_splited[1], my_1d_array_random_splited[2])
print(dot_product)

8125


In [45]:
Two_d_array = np.random.randint(500, size=(6, 4))
print(Two_d_array)
print(
    Two_d_array.T
)

[[394 154 459 282]
 [ 55 466 389 203]
 [ 48 342 380 163]
 [262 478 226  94]
 [295 493 262 225]
 [ 17 388 411 379]]
[[394  55  48 262 295  17]
 [154 466 342 478 493 388]
 [459 389 380 226 262 411]
 [282 203 163  94 225 379]]


In [46]:
oned_array = np.random.randint(1000, size=(50,))
print(oned_array)

[997 997  29 238 377  41  57 467 439  56 229 275 261 866 826 310 860 758
 697 595 186 645 553  17 615 819 477 109 965 350  11 399  28 109  87 204
 414  81 229 844 100 143 410 517 401 977 582 836 188 683]


In [51]:
def filter_method(x):
    if x % 2 ==0:
        return True
    else:
        return False
filter_iterable = filter(filter_method, oned_array)
filtered_array = np.array(list(filter_iterable))
print(filtered_array)

[238  56 866 826 310 860 758 186 350  28 204 414 844 100 410 582 836 188]
