In [1]:
import numpy as np


Numpy array iteration

In [2]:
my_np_array = np.array(
    [1, 2, 3, 4, 5, 6, 7, 8]
)
print(my_np_array)

[1 2 3 4 5 6 7 8]


In [ ]:
"""option - 1 Iterate by Value"""

In [3]:
for val in my_np_array:
    print(val)

1
2
3
4
5
6
7
8


In [7]:
"""Option 2 Iterate by Index"""
for i in range(len(my_np_array)):
    print(i)
#    print(my_np_array[i])

0
1
2
3
4
5
6
7


In [11]:
"""Option - 3 Iterate by value and index"""
for i, val in enumerate(my_np_array):
#    print(i, val)
    print(f"index = {i} value = {val}")

index = 0 value = 1
index = 1 value = 2
index = 2 value = 3
index = 3 value = 4
index = 4 value = 5
index = 5 value = 6
index = 6 value = 7
index = 7 value = 8


Array Reshaping

In [16]:
"""Array Reshaping"""
my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12],
     [13, 14, 15]]
)
print(my_2d_array)
print(my_2d_array.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)


In [23]:
my_2d_array_reshaped = my_2d_array.reshape(3, 5)
print(my_2d_array_reshaped)
print(my_2d_array_reshaped.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [24]:
"""array reshaping with -1"""
my_2d_array_zeros = np.zeros(shape=(3, 4, 2, 2))
print(my_2d_array_zeros)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [27]:
my_2d_array_zeros_reshaped = my_2d_array_zeros.reshape(2, 2, -1)
print(my_2d_array_zeros_reshaped)
print(my_2d_array_zeros_reshaped.shape)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(2, 2, 12)


In [3]:
"""Sorting"""
import numpy as np
probabilities = np.array(
    [0.3, 0.2, 0.4, 0.1, 0.5]
)
print(probabilities)
probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)
"""Reverse sorting"""
probabilities_sorted_reversed = np.sort(probabilities)[: : -1]
print(probabilities_sorted_reversed)


[0.3 0.2 0.4 0.1 0.5]
[0.1 0.2 0.3 0.4 0.5]
[0.5 0.4 0.3 0.2 0.1]


In [6]:
"""" Argmax and argmin """
index_max = np.argmax(probabilities)
print(index_max)
index_min = np.argmin(probabilities)
print(index_min)

4
3


In [9]:
"""Array Slicing """
my_num_array = np.array(
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
)
New_num_array = np.split(
    my_num_array,
    indices_or_sections=5
)
print(New_num_array)
print(New_num_array[0])
print(New_num_array[1])
print(New_num_array[2])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]
[1 2 3]
[4 5 6]
[7 8 9]


In [12]:
 """" Dot Product """
my_array_1 = np.array([1, 5, 6])
my_array_2 = np.array([3, 6, 2])
print(my_array_1, my_array_2)
dot_product = np.dot(my_array_1, my_array_2)
dot_product_2 = np.dot([4, 5, 2], my_array_1)
print(dot_product)
print(dot_product_2)

[1 5 6] [3 6 2]
45
41


In [17]:
""""Matrix Transpose"""
my_2d_array1 = np.array([
    [1, 3, 4, 8],
    [2, 8, 4, 3]]
)
print(my_2d_array1)
print(my_2d_array1.shape)
print(my_2d_array1.T)
print(my_2d_array1.T.shape)

[[1 3 4 8]
 [2 8 4 3]]
(2, 4)
[[1 2]
 [3 8]
 [4 4]
 [8 3]]
(4, 2)


In [21]:
""""Mean, Median and Standard Deviation"""
print(my_num_array)
print(np.mean(my_num_array))
print(np.median(my_num_array))
print(np.std(my_num_array))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
8.0
8.0
4.320493798938574


Numpy Filtering

In [24]:
""""Option 1 Boolean Mask"""
print(my_num_array)
my_num_array_splited = np.split(
    my_num_array,
    indices_or_sections=3
)
print(my_num_array_splited)
Boolean_mask = [True, False, False, True, True]
my_filtered_array = my_num_array_splited[1][Boolean_mask]
print(my_filtered_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]
[ 6  9 10]


In [2]:
import numpy as np
my_num_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(my_num_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [3]:
import numpy as np
filter_mask = (my_num_array % 2 ==1)
print(filter_mask)
filtered_array = my_num_array[filter_mask]
print(filtered_array)

[ True False  True False  True False  True False  True False  True False
  True False  True]
[ 1  3  5  7  9 11 13 15]


In [4]:
""""Custom filtered Method"""
def filter_method(x):
    if x % 2 ==0:
        return False
    else:
        return True
filter_iterable = filter(filter_method, my_num_array)
filtered_array = np.array(
    list(filter_iterable)
)
print(filtered_array)

[ 1  3  5  7  9 11 13 15]


In [5]:
new_array = np.arange(start=0, stop=50, step=1)
print(new_array)
new_array2 = np.arange(start= 30, stop=78, step= 1)
print(new_array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77]


In [8]:
def filter_array(y):
    if y % 2 ==1:
        return False
    else:
        return True
filter_iterable = filter(filter_array, new_array)
filtered_array = np.array(list(filter_iterable))
print(filtered_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [10]:
def filtered_array(t):
    if t % 2 ==0:
        return False
    else:
        return True
filtered_iterable = filter(filtered_array, new_array2)
filtered_array2 = np.array(list(filtered_iterable))
print(filtered_array2)

[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77]


In [13]:
for x in new_array2:
    x = x + 5
print(x)
New_array = new_array2 + 5
print(New_array)

82
[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82]


In [14]:
w = np.array(
    [1, 2, 3]
)
y = np.array(
    [[4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
     [13, 14, 15]]
)
print(w * y)

[[ 4 10 18]
 [ 7 16 27]
 [10 22 36]
 [13 28 45]]
