In [1]:
import numpy as np
from packaging.specifiers import Specifier

In [2]:
np.__version__

'2.3.4'

In [3]:
My_NP_array = np.array([1,2,3,4,5,6,7,8,9])
print(My_NP_array)

[1 2 3 4 5 6 7 8 9]


In [4]:
print(type(My_NP_array))

<class 'numpy.ndarray'>


In [5]:
My_NP_array.dtype

dtype('int64')

In [6]:
My_NP_array.shape

(9,)

In [7]:
My_NP_array.ndim

1

In [8]:
""" Create an array with all zeros"""
Zeros = np.zeros(
    shape=(5,)
)
print(Zeros)

[0. 0. 0. 0. 0.]


In [11]:
""" Create an array with all ones"""
Ones = np.ones(
    shape=(4,),
    dtype=int
)
print(Ones)

[1 1 1 1]


In [14]:
""" Create an array with specific value"""
specific_value = np.full(
    shape=(5,6),
    fill_value=3)
print(specific_value)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


In [16]:
""" Create an indentity matrix"""
Indentity_matrix = np.eye(
    3,
    dtype=int
)
print(Indentity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
""" Create an empty array"""
My_empty_array = np.empty(
    shape=(4,)
)
print(My_empty_array)
print(My_empty_array.dtype)

[1. 1. 1. 1.]
float64


In [21]:
""" Type Casting"""
My_empty_array_int = My_empty_array.astype("int"
)
print(My_empty_array_int)
print(My_empty_array_int.dtype)

[1 1 1 1]
int64


In [22]:
""" Create a sequential array"""
My_array = np.arange(start=2, stop=11, step=2)
print(My_array)

[ 2  4  6  8 10]


In [24]:
My_linespace_array = np.linspace(start=0, stop=15, num=3, dtype=int)
print(My_linespace_array)

[ 0  7 15]


In [2]:
import numpy as np
My_0d_array = np.array(32)
print("0d_array: ", My_0d_array, "Number_of_dimension: ", My_0d_array.ndim)

0d_array:  32 Number_of_dimension:  0


In [4]:
My_1d_array = np.array([1,2,3,4,5,6])
print("1d_array: ", My_1d_array, "Number_of_dimension: ", My_1d_array.ndim)

1d_array:  [1 2 3 4 5 6] Number_of_dimension:  1


In [6]:
My_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("2d_array: ", My_2d_array, "Number_of_dimension: ", My_2d_array.ndim)

2d_array:  [[1 2 3 4]
 [5 6 7 8]] Number_of_dimension:  2
